__END__

=head1 NAME

check_adaptec_raid - nagios/icinga plugin to check adaptec raid controllers

=head1 SYNOPSIS

Example:

	./check_adaptec_raid -T 30,40 -C 1 -LD 0,1 -PD 1 -z 0
	AACRAID CRITICAL (Ctrl #1): [Ctrl. Status critical, Ctrl. temp. critical, Log. device failed/degraded,]

=head1 VERSION

This document describes plugin version 0.1

=head1 DESCRIPTION

check_adaptec_raid is a Nagios/Icinga Plugin to check Adaptec Raid Controllers for errors/warnings.
This plugin makes heavy use of 'arcconf' which can be obtained from the Adaptec Homepage. It checks the controller, the physical devices and the logical devices seperately for errors or warnings(For more detailed information about what is beeing monitored see METHODS).

=head1 DEPENDENCIES

- This plugin requires a running Nagios or Icinga. (either local or NRPE)

- sudo 

- arcconf (Can be obtained from the Adaptec Homepage)

- the following Perl Modules:

	use strict;
	use warnings;
	use Getopt::Long qw(:config no_ignore_case);
	use Data::Dumper;
	use Switch 'Perl6';

=head1 METHODS

=head2 myStatus

Sets the correct exit code for each function.
Can only increment the Exit code (if necessary) since the exit code may not change from Warning to Ok.

=head2 displayUsage

Explains the Usage of the plugin and which parameters are available.

=head2 displayHelp

Prints a short help text and quick information where to find additional help.

=head2 displayVersion

Prints the Plugin Version and the arcconf version.

=head2 getControllerCfg

Checks the Adaptec Raid Controller for Controller Errors. (uses arcconf GETCONFIG 1 AD)

- Controller Status

- Defunctional Disks

- Logical Devices which have failed/are degraded

- Temperature

- Status of ZMM if present 

The controller temperature can be set to a warning/critical level (parameter: -T|--temperature).
If no ZMM Module is present the check can be disabled (--zmm 0).

=head2 getPhysDevCfg 

Returns Information about physical Devices attached to the Adaptec Raid-Controller:

- Disk Status

- S.M.A.R.T. Status

- S.M.A.R.T. Warnings

- Low-RPM Warnings

- Failed Disk Segments

=head2 getLogDevCfg

Returns Information about logical Devices:

- General Logical Devices Status

- Failed Stripes

TODO: Description

=head1 LICENSE AND COPYRIGHT

Copyright (c) 2013,
Martin Grubhofer C<< <mgrubhofer@thomas-krenn.com> >>.
Franz Nemeth C<< <fnemeth@thomas-krenn.com> >>.
All rights reserved.

This module is free software; you can redistribute it and/or
modify it under the same terms as Perl itself. See L<perlartistic>.

=head1 DISCLAIMER OF WARRANTY

BECAUSE THIS SOFTWARE IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY
FOR THE SOFTWARE, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN
OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES
PROVIDE THE SOFTWARE "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER
EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE
ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE SOFTWARE IS WITH
YOU. SHOULD THE SOFTWARE PROVE DEFECTIVE, YOU ASSUME THE COST OF ALL
NECESSARY SERVICING, REPAIR, OR CORRECTION.

IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY AND/OR
REDISTRIBUTE THE SOFTWARE AS PERMITTED BY THE ABOVE LICENCE, BE
LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL,
OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE
THE SOFTWARE (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING
RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A
FAILURE OF THE SOFTWARE TO OPERATE WITH ANY OTHER SOFTWARE), EVEN IF
SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF
SUCH DAMAGES.